# fly.toml app configuration file generated for portim on 2024-12-28T19:55:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portim"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

[env]
  LOG_LEVEL = "debug"
  NODE_ENV = "production"
  FASTIFY_ADDRESS = "0.0.0.0"
  PORT = "3000"
  SUPABASE_URL = "https://agjotokcbloccmkpphqi.supabase.co"
