name: CI and Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install PNPM so we can run pnpm commands
      - name: Install pnpm
        run: npm install -g pnpm@9.15.1

      # Install dependencies
      - name: Install Dependencies
        run: pnpm install

      # Run Tests
      - name: Run Tests
        run: pnpm test

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: test  # Only run this job if 'test' passes
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
